In [5]:
import numpy as np
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']

In [6]:
np.arange(0, 20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [7]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [8]:
a = np.array([[1,2],[3,4]])

In [9]:
np.transpose(a
             )

array([[1, 3],
       [2, 4]])

In [10]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]

In [11]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]

In [12]:
import numpy as np
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,32,93,39]))
demo_matrix[2,3]

39

In [13]:
import pandas as pd
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])

In [ ]:
pd.concat([s1,s2])

0    a
1    b
0    c
1    d
dtype: object

In [ ]:
import numpy as np
demo_array = np.arange(10,17)
demo_array [:]= 101
demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [ ]:
import pandas as pd
score = [10, 15, 20, 25]
pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [ ]:
import pandas
import seaborn as sns
data=sns.load_dataset('tips')

In [ ]:
pd.pivot_table(data=data, values='total_bill', index='sex', columns='day', aggfunc='mean')

day          Thur        Fri        Sat        Sun
sex
Male    18.714667  19.857000  20.802542  21.887241
Female  16.715312  14.145556  19.680357  19.872222

In [ ]:
pandas.pivot_table(data=data, values='total_bill', index='day', columns='sex', aggfunc='mean')

sex        Male     Female
day
Thur  18.714667  16.715312
Fri   19.857000  14.145556
Sat   20.802542  19.680357
Sun   21.887241  19.872222

In [ ]:
pandas.pivot_table(data=data, values='day', index='sex', columns='total_bill', aggfunc='mean')

C:\Users\rers9\AppData\Local\Temp\ipykernel_1092\2585661749.py:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  pandas.pivot_table(data=data, values='day', index='sex', columns='total_bill', aggfunc='mean')

Empty DataFrame
Columns: []
Index: [Male, Female]

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from scipy.stats import binom
binom.pmf(k = 7,n = 10, p = 0.6)

0.21499084799999987

In [ ]:
from scipy.stats import binom
1 - binom.cdf(k = 5,n = 15, p = 0.75)

0.9992050509899855

In [ ]:
from scipy.stats import binom
1 - binom.pmf(k = 6,n = 15, p = 0.75)

0.9966019345447421

In [ ]:
from scipy.stats import norm

norm.cdf(590,502,115) - norm.cdf(400,502,115)

0.5903777927789047

In [ ]:
from scipy.stats import t

norm.interval(0.95, loc = 180, scale = 36)

(109.44129655655806, 250.55870344344194)

In [ ]:
import numpy as np

np.random.randint(0,2)

0

In [ ]:
import numpy as np

In [ ]:
a = [[2,1],[3,4]]

In [ ]:
len(a)

2

In [ ]:
a = 2
input(a)

'a'

In [ ]:
input("adgas","fdsafdsaf")

TypeError: raw_input() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
"a"+"b"

'ab'

In [ ]:
for i in range(2):
    print(i)

0
1

In [ ]:
sum(["a","b"])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
"sadfsdaf".find("a")

1

In [ ]:
barco  = [[1,2,3],[4,5,6],[7,8,9]]
barco[:][2]

[7, 8, 9]

In [ ]:
a = "asd"

In [ ]:
a.find("sd")

1

In [ ]:
a.find("c")

-1

In [ ]:
import math

In [ ]:
math.perm(4,2)

12

In [ ]:
math.ceil(2.5)

3

In [ ]:
def climbStairs( n):
        prev = 1
        prev2 = 0
        for i in range(1, n+1):
            curi = prev + prev2
            prev2 = prev
            prev = curi
        return prev

In [ ]:
climbStairs(7)

21

In [ ]:
def climbStairs(n: int) -> int:
        prev = 1
        prev_prev = 0
        for _ in range(n):
            prev_prev, prev = prev, prev + prev_prev
        return prev

In [ ]:
climbStairs(7)

NameError: name 'climbStairs' is not defined

In [ ]:
import os
os.path.isfile("curso.py")

True

In [8]:
with open('archivo.txt','w') as txt:
    txt.write("-- Personajes --\n")
    txt.write("-- Usuarios --\n")

In [20]:
with open('archivo.txt','r+') as txt:
    asd = txt.readlines()

asd.index("-- Usuarios --\n")
asd.insert(1,"usuario1"+"\n")

In [21]:
with open('archivo2.txt','w') as txt:
    txt.writelines(asd)

In [22]:
# ventana 109
#283
#294
a = [1,2]

In [23]:
a

[1, 2]

In [25]:
a.append((3,4))

In [26]:
a

[1, 2, (3, 4)]

In [27]:
(3,4) in a

True

In [28]:
import random

mylist = ["apple", "banana", "cherry"]
random.shuffle(list(random.shuffle(mylist)))

print(mylist)

TypeError: 'NoneType' object is not iterable

In [29]:
a = []

In [30]:
a.pop()

IndexError: pop from empty list

In [1]:
print("$",end="")

$